routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use MichalPalus1\Rareadmin\Http\Controllers\UniversalController;
use MichalPalus1\Rareadmin\Http\Controllers\SuperAdminController;

Route::name('admin.')->prefix('admin')->group(function () {

    Route::get('/', [UniversalController::class, 'index'])->name('index');

    Route::get('/sign_out_as', [UniversalController::class, 'sign_out_as'])->name('sign_out_as');

    Route::get('/ajax/{entities_name}', [UniversalController::class, 'entities_ajax'])->name('entities_ajax');
    Route::get('/{entities_name}', [UniversalController::class, 'entities'])->name('entities');
    Route::get('/{entities_name}/form/{id?}', [UniversalController::class, 'entity_form'])->name('entity_form');
    Route::post('/{entities_name}/store/{id?}', [UniversalController::class, 'entity_store'])->name('entity_store');
    Route::get('/{entities_name}/delete/{id}', [UniversalController::class, 'entity_delete'])->name('entity_delete');
    Route::get('/{entities_name}/import', [UniversalController::class, 'entity_import'])->name('entity_import');
    Route::post('/{entities_name}/import_preview', [UniversalController::class, 'entity_import_preview'])->name('entity_import_preview');
    Route::post('/{entities_name}/import_proccess', [UniversalController::class, 'entity_import_proccess'])->name('entity_import_proccess');

});


Route::name('superadmin.')->prefix('superadmin')->group(function () {

    Route::get('/', [SuperAdminController::class, 'index'])->name('index');
    Route::get('/sign_in_as/{user}', [SuperAdminController::class, 'sign_in_as'])->name('sign_in_as');

    Route::get('/entities', [SuperAdminController::class, 'entities'])->name('entities');
    Route::get('/entity/form/{entity?}', [SuperAdminController::class, 'entity_form'])->name('entity_form');
    Route::post('/entity/store/{entity?}', [SuperAdminController::class, 'entity_store'])->name('entity_store');
    Route::get('/entity/delete/{entity}', [SuperAdminController::class, 'entity_delete'])->name('entity_delete');


    Route::get('/types', [SuperAdminController::class, 'types'])->name('types');


    Route::get('/restrictions', [SuperAdminController::class, 'restrictions'])->name('restrictions');
    Route::get('/restriction/form/{restriction?}', [SuperAdminController::class, 'restriction_form'])->name('restriction_form');
    Route::post('/restriction/store/{restriction?}', [SuperAdminController::class, 'restriction_store'])->name('restriction_store');
    Route::get('/restriction/delete/{restriction}', [SuperAdminController::class, 'restriction_delete'])->name('restriction_delete');


    Route::get('/identify', [SuperAdminController::class, 'identify'])->name('identify');

});

resources/views/admin/entities.blade.php
@extends('rareadmin::layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0"> {{$entity->title}} @if(can('create', $entity, 'Entity')) <a href="{{route('admin.entity_form', ['entities_name' => $entities_name])}}"><button class="btn btn-success"><i class="fa fa-plus"></i> @lang('Add')</button></a>@endif</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Admin</a></li>
                        <li class="breadcrumb-item active">{{$entity->title}}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th></th>
                                    {{getColumns($entities_name, 'table')}}
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection

@section('js')
    <script>

        $('.table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: '{!! route('admin.entities_ajax', $entities_name) !!}',
            columns: [
                {{getColumns($entities_name, 'js')}}
            ],
            columnDefs: [
                {
                    render: function ( data, type, row ) {

                        var str = '';

                        @if(can('edit', $entity, 'Entity'))
                            str +=  '<a href="' + '{{route('admin.entity_form', ['entities_name' => $entities_name, 'id' => 'XXX'])}}'.replace('XXX', row['id']) + '">' +
                                        '<button class="btn btn-sm btn-primary">@lang('Edit')</button>' +
                                    '</a> ';
                        @endif

                        @if(can('delete', $entity, 'Entity'))
                            str +=  '<a href="' + '{{route('admin.entity_delete', ['entities_name' => $entities_name, 'id' => 'XXX'])}}'.replace('XXX', row['id']) + '" onclick="return confirm(\'@lang('Are you sure you want to delete this entity?')\')">' +
                                        '<button class="btn btn-sm btn-danger">@lang('Delete')</button>' +
                                    '</a>';
                        @endif

                        return str;
                    },
                    targets: 0
                }
            ]
        });

    </script>
@endsection

resources/views/admin/entity_form.blade.php
@extends('rareadmin::layouts.app')

@php($ent_for_assets = \MichalPalus1\Rareadmin\Models\Entity::with('columns.type')->where('name', $entities_name)->first())

@section('content')

    @if($ent_for_assets && $ent_for_assets->columns && in_array('wysiwyg', $ent_for_assets->columns->pluck('type.name')->toArray()))
        <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    @endif

    @if($ent_for_assets && $ent_for_assets->columns && in_array('code', $ent_for_assets->columns->pluck('type.name')->toArray()))
        <link href="https://cdn.jsdelivr.net/npm/codemirror@5.65.2/lib/codemirror.css" rel="stylesheet">
    @endif

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{{\MichalPalus1\Rareadmin\Models\Entity::where('name', $entities_name)->first()->title}} > @if($entity->id) @lang('Edit') @else @lang('Add') @endif</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Admin</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.entities', ['entities_name' => $entities_name])}}">{{\MichalPalus1\Rareadmin\Models\Entity::where('name', $entities_name)->first()->title}}</a></li>
                        <li class="breadcrumb-item active">@if($entity->id) @lang('Edit') @else @lang('Add') @endif</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <form method="post" action="{{route('admin.entity_store', ['entities_name' => $entities_name, 'id' => $entity->id])}}" enctype="multipart/form-data">
                                @csrf
                                {{getColumns($entities_name, 'form', $entity)}}
                                <button type="submit" class="btn btn-primary btn-lg">@lang('Save')</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection

@section('js')

    @if($ent_for_assets && $ent_for_assets->columns && in_array('wysiwyg', $ent_for_assets->columns->pluck('type.name')->toArray()))

        <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

        <script>
            $(document).ready(function() {
                $('.summernote').summernote();
            });
        </script>
    @endif

    @if($ent_for_assets && $ent_for_assets->columns && in_array('code', $ent_for_assets->columns->pluck('type.name')->toArray()))

        <script src="https://cdn.jsdelivr.net/npm/codemirror@5.65.2/lib/codemirror.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/codemirror@5.65.2/mode/clike/clike.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/codemirror@5.65.2/mode/php/php.js"></script>

        <script>
            var editor = CodeMirror.fromTextArea(document.getElementsByClassName('codemirror')[0], {
                mode: "text/x-php",
                lineNumbers: true,
                indentUnit: 4,
                indentWithTabs: true
            });
        </script>
    @endif

@endsection

resources/views/admin/entity_import.blade.php
@extends('rareadmin::layouts.app')

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{{\MichalPalus1\Rareadmin\Models\Entity::where('name', $entities_name)->first()->title}} > @lang('Import')</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Admin</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.entities', ['entities_name' => $entities_name])}}">{{\MichalPalus1\Rareadmin\Models\Entity::where('name', $entities_name)->first()->title}}</a></li>
                        <li class="breadcrumb-item active">@lang('Import')</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form id="import" enctype="multipart/form-data">
                                <h1>@lang('Select file'):</h1>
                                <input type="file" name="importFile" id="importFile">
                            </form>
                            <form method="POST" action="{{route('admin.entity_import_proccess', ['entities_name' => $entities_name])}}" id="import_final" style="margin-top: 40px; display: none">

                                @csrf

                                <h1>@lang('Data preview & reorder'):</h1>
                                <table class="table" id="preview_table">
                                    <thead>
                                    <tr></tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>

                                <h2 style="margin-top: 40px">@lang('Final Import settings'):</h2>

                                <div class="form-group row">
                                    <label for="input_skip_first_row" class="col-sm-4 col-form-label">@lang('Skip first row?')</label>
                                    <div class="col-sm-8">
                                        <input type="checkbox" name="skip_first_row" style="width:40px" class="form-control" id="input_skip_first_row" value="1">
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary btn-lg">@lang('Proccess Import')</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection

@section('js')
    <script>

        function get_option_html(current, all) {
            var html = '';
            $(all).each(function (index) {
                if (all[index] == current) {
                    html += '<option selected value="' + all[index] + '">' + all[index] + '</option>';
                } else {
                    html += '<option value="' + all[index] + '">' + all[index] + '</option>';
                }
            });

            return html;
        }

        $('#importFile').on('change', function () {
            $.ajax({
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();

                    xhr.upload.addEventListener("progress", function (evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = evt.loaded / evt.total;
                            percentComplete = parseInt(percentComplete * 100);

                            Swal.fire({
                                text: percentComplete+"% done.",
                                timer: 500,
                                button: false
                            });

                            if (percentComplete === 100) {
                                Swal.fire({
                                    icon: "success",
                                    timer: 1500,
                                });
                            }

                        }
                    }, false);

                    return xhr;
                },
                url: '{{route('admin.entity_import_preview', ['entities_name' => $entities_name])}}',
                type: "POST",
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                data: new FormData($('#import')[0]),
                cache: false,
                contentType: false,
                processData: false,
                success: function (result) {
                    $('#import_final').show();

                    $(result.data[0]).each(function (index) {
                        $('#preview_table thead tr').append('<th><select name="order[]"><option value="null">@lang('Skip')</option>'+get_option_html(result.columns[index], result.columns)+'</th>');
                    });

                    $(result.data).each(function (index) {
                        $('#preview_table tbody').append('<tr></tr>');

                        $(result.data[index]).each(function (index2) {
                            $('#preview_table tbody tr:last-child').append('<td>'+result.data[index][index2]+'</td>');
                        });
                    });
                }
            });
        });
    </script>
@endsection

resources/views/admin/index.blade.php
@extends('rareadmin::layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0"> @lang('Dashboard')</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Admin</a></li>
                        <li class="breadcrumb-item active">@lang('Dashboard')</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container">
            <div class="row">
                @foreach(\MichalPalus1\Rareadmin\Models\Entity::all() as $entity)
                    @if(can('view', $entity, 'Entity'))
                        <div class="col-lg-4">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title w-100">{{$entity->title}} <span class="float-right">({{get_model($entity->name)->count()}})</span></h5>
                                    <div class="pt-5">
                                        <a href="{{route('admin.entities', ['entities_name' => $entity->name])}}">
                                            <button class="btn btn-sm btn-success">@lang('Show')</button>
                                        </a>
                                        @if(auth()->user()->role->name == 'superadmin')
                                            <a href="{{route('superadmin.entity_form', $entity)}}">
                                                <button class="btn btn-sm btn-primary">@lang('Manage')</button>
                                            </a>
                                        @endif
                                        <a href="{{route('admin.entity_import', ['entities_name' => $entity->name])}}">
                                            <button class="btn btn-sm btn-secondary">@lang('Import')</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endif
                @endforeach
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RareAdmin.com - Simple Laravel Admin Panel</title>
    <icon rel="icon" href="{{asset('rareadmin/favicon.ico')}}" type="image/x-icon">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.bootstrap4.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('rareadmin/css/adminlte.min.css')}}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css">

    <style>
        .select2-selection {
            height: 40px !important;
        }
        .select2-container--default .select2-selection--single, .select2-container--default .select2-selection--multiple {
            background: none;
            border-color: #6c757d;
        }
        .select2-container--default .select2-selection--single .select2-selection__rendered {
            color: white;
            padding-left: 0;
        }
        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            color: black;
            padding-left: 24px;
        }
        .select2-selection--multiple .select2-search__field {
            height: 26px !important;
            padding-left: 4px !important;
            border-radius: 4px;
            border: 1px solid #aaa;
        }
        .select2-container--default .select2-results__option--selected {
            background-color: #3f474e !important;
        }
    </style>
</head>
<body class="hold-transition dark-mode">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand-md navbar-dark">
        <div class="container">
            <a href="#0" class="navbar-brand" data-widget="pushmenu">
                <span class="brand-text font-weight-light">
                    <img src="https://rareadmin.com/assets/img/ra_logo.png" alt="RareAdmin Logo" style="height: 30px;">
                </span>
            </a>

            <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    @if(auth()->check())
                        <li class="nav-item">
                            <a href="{{route('admin.index')}}" class="nav-link"><i class="nav-icon fas fa-th"></i> @lang('Dashboard')</a>
                        </li>
                    @endif
                    @foreach(\MichalPalus1\Rareadmin\Models\Entity::where('show_in_top_menu', true)->get() as $entity)
                        @if(can('view', $entity, 'Entity'))
                            <li class="nav-item">
                                <a href="{{route('admin.entities', ['entities_name' => $entity->name])}}" class="nav-link"><i class="nav-icon fas {{$entity->icon}}"></i> {{$entity->title}}</a>
                            </li>
                        @endif
                    @endforeach
                </ul>

            </div>
        </div>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{{route('admin.index')}}" class="brand-link">
            <span class="brand-text font-weight-light">
                <img src="https://rareadmin.com/assets/img/ra_logo.png" alt="RareAdmin Logo" style="height: 30px;">
            </span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    @if(auth()->check())
                        @if(auth()->user()->role->name == 'superadmin')
                            <li class="nav-item has-treeview menu-open">
                                <a href="javascript:" class="nav-link">
                                    <i class="nav-icon fas fa-user"></i>
                                    <p>
                                        Superadmin
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="{{route('superadmin.index')}}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>
                                                @lang('RareAdmin Dashboard')
                                            </p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{route('superadmin.entities')}}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>@lang('Entities')</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{route('superadmin.types')}}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>@lang('Input types')</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{route('superadmin.restrictions')}}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>@lang('Permissions')</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <div class="user-panel mb-1"></div>
                        @endif
                    @else
                        <li class="nav-item">
                            <a href="{{route('login')}}" class="nav-link">
                                <i class="nav-icon fas fa-sign-in"></i>
                                <p>@lang('Log in')</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('register')}}" class="nav-link">
                                <i class="nav-icon fas fa-user-plus"></i>
                                <p>@lang('Sign up')</p>
                            </a>
                        </li>
                    @endif
                    @foreach(\MichalPalus1\Rareadmin\Models\Entity::get() as $entity)
                        @if(can('view', $entity, 'Entity'))
                            <li class="nav-item">
                                <a href="{{route('admin.entities', ['entities_name' => $entity->name])}}" class="nav-link">
                                    <i class="nav-icon fas {{$entity->icon}}"></i>
                                    <p>{{$entity->title}}</p>
                                </a>
                            </li>
                        @endif
                    @endforeach

                    <div class="user-panel"></div>

                    <li class="nav-item">
                        @if(auth()->check())
                            <small class="ml-3">@lang('Signed in as') {{auth()->user()->name}}</small>
                        @endif
                        @if(session()->exists('prev_login'))
                            <a href="{{route('admin.sign_out_as')}}" class="nav-link">
                                <i class="nav-icon fas fa-sign-out-alt"></i>
                                <p>@lang('Log out')</p>
                            </a>
                        @else
                            @if(auth()->check())
                                <a href="#" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="nav-link">
                                    <i class="nav-icon fas fa-sign-out-alt"></i>
                                    <p>@lang('Log out')</p>
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            @endif
                        @endif
                    </li>

                    <div class="user-panel mb-1"></div>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->

        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        @yield('content')
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Rare Admin Panel v 1.1
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; {{date('Y')}} <a href="https://rareadmin.com">RareAdmin.com</a>.</strong> All rights reserved.
    </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<!-- Bootstrap 4 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="{{asset('rareadmin/js/adminlte.min.js')}}"></script>
{{--<script src="/js/demo.js"></script>--}}
<script src="https://cdn.datatables.net/2.0.3/js/dataTables.min.js"></script>
<script src="https://cdn.datatables.net/2.0.3/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

<script>
    @if(session()->has('success'))

    Swal.fire({
        title: "{{session()->get('success')}}",
        icon: "success",
        timer: 1500,
    });

    @endif


    @if(session()->has('error'))

    Swal.fire({
        title: "{{session()->get('error')}}",
        icon: "error",
    });

    @endif

    $(document).ready(function() {
        $('.select2').select2();
    });
</script>

@yield('js')

</body>
</html>